name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with: 
          severity: error
          text: Build failed
          description: commit ${{ github.event.head_commit }} broke the build
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: test
        run: npm test
      - name: Render Deployment
        if: ${{ github.event_name == 'push' && !contains( join(github.event.commits.*.message, ', '), '#skip')}} 
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Deploy success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with: 
          severity: info
          text: A new version of Pokedex deployed
          description: description -> pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains( join(github.event.commits.*.message, ', '), '#skip')}}
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
    
